name: iOS starter workflow

on:
  push:
    branches:
      - main
      - Develop/*
      - Sprint3/*
  pull_request:
    branches: 
      - main
      - Develop/*
      - Sprint3/*
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Debug folder
        run: |
          pwd
          ls -R .
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          project=$(find . -name "*.xcodeproj" | head -1)
          workspace=$(find . -name "*.xcworkspace" | head -1)
          project=$(find . -name "*.xcodeproj" | head -1) 
          echo "Found project: $project" 
          if [ -z "$project" ]; then 
            echo "ERROR: Nenhum .xcodeproj encontrado!" 
            exit 1 
          fi
          echo "Using $filetype_parameter: $file_to_build"
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed -e "s/ Simulator$//")
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          project=$(find . -name "*.xcodeproj" | head -1)
          workspace=$(find . -name "*.xcworkspace" | head -1)
          if [ -n "$workspace" ]; then
            filetype_parameter="workspace"
            file_to_build="$workspace"
          else
            filetype_parameter="project"
            file_to_build="$project"
          fi
          xcodebuild build-for-testing \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=$platform,name=$device"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed -e "s/ Simulator$//")
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          project=$(find . -name "*.xcodeproj" | head -1)
          workspace=$(find . -name "*.xcworkspace" | head -1)
          if [ -n "$workspace" ]; then
            filetype_parameter="workspace"
            file_to_build="$workspace"
          else
            filetype_parameter="project"
            file_to_build="$project"
          fi
          xcodebuild test-without-building \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination "platform=$platform,name=$device"
      
